import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import { Box } from "@mui/material";
import Sidebar from "@/components/Sidebar";
const ReduxProvider = dynamic(() => import("./redux-provider"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs-Assignment",
  description: "Generated by Majid Khan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Box sx={{ display: "flex" }}>
            <Sidebar />

            <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
              {children}
            </Box>
          </Box>
        </ReduxProvider>
      </body>
    </html>
  );
}
